// apps/interactive-benchmark-react/src/App.jsx
import React, { useState, useCallback, useRef, useEffect } from 'react';
import Grid from './Grid';
import './App.css';

let idCounter = 1;

const buildData = (count) => {
    const data = [];
    for (let i = 0; i < count; i++) {
        data.push({
            id: idCounter++,
            label: `row ${idCounter}`,
        });
    }
    return data;
};

function App() {
    const [data, setData] = useState([]);
    const [selected, setSelected] = useState(null);
    const feedInterval = useRef(null);

    const create1k = () => {
        idCounter = 1;
        setData(buildData(1000));
    };
    const create10k = () => {
        idCounter = 1;
        setData(buildData(10000));
    };
    const update = () => {
        const newData = [...data];
        for (let i = 0; i < newData.length; i += 10) {
            newData[i] = { ...newData[i], label: newData[i].label + ' updated' };
        }
        setData(newData);
    };
    const select = () => {
        if (data.length > 0) {
            const randomIndex = Math.floor(Math.random() * data.length);
            setSelected(data[randomIndex].id);
        }
    };
    const swap = () => {
        if (data.length > 1) {
            const newData = [...data];
            const index1 = Math.floor(Math.random() * data.length);
            let index2 = Math.floor(Math.random() * data.length);
            while (index1 === index2) {
                index2 = Math.floor(Math.random() * data.length);
            }
            [newData[index1], newData[index2]] = [newData[index2], newData[index1]];
            setData(newData);
        }
    };
    const remove = () => {
        if (data.length > 0) {
            const newData = [...data];
            const index = Math.floor(Math.random() * data.length);
            newData.splice(index, 1);
            setData(newData);
        }
    };
    const clear = () => {
        setData([]);
        idCounter = 1;
    };

    const runHeavy = () => {
        console.log('Heavy calculation started in Main Thread...');
        let result = 0;
        const iterations = 50000000;
        for (let i = 0; i < iterations; i++) {
            result += Math.sqrt(i) * Math.sin(i) / Math.cos(i) + Math.log(i + 1);
        }
        console.log('Heavy calculation finished in Main Thread. Result:', result);
    };

    const runHeavyTask = () => {
        const worker = new Worker(new URL('./heavy-task.js', import.meta.url));
        console.log('Heavy calculation started in Task Worker...');
        worker.onmessage = (e) => {
            console.log('Heavy calculation finished in Task Worker. Result:', e.data);
            worker.terminate();
        };
        worker.postMessage(50000000);
    };

    const toggleFeed = () => {
        if (feedInterval.current) {
            clearInterval(feedInterval.current);
            feedInterval.current = null;
            console.log('Real-time feed stopped.');
        } else {
            console.log('Real-time feed started.');
            feedInterval.current = setInterval(() => {
                setData(currentData => {
                    const newData = [...currentData];
                    const updateCount = 100;
                    for (let i = 0; i < updateCount; i++) {
                        const randomIndex = Math.floor(Math.random() * newData.length);
                        if (newData[randomIndex]) {
                            newData[randomIndex] = { ...newData[randomIndex], label: `updated ${newData[randomIndex].id} at ${new Date().toLocaleTimeString()}` };
                        }
                    }
                    return newData;
                });
            }, 16);
        }
    };

    useEffect(() => {
        return () => {
            if (feedInterval.current) {
                clearInterval(feedInterval.current);
            }
        };
    }, []);

    return (
        <div className="app-container">
            <div className="button-container">
                <button onClick={create1k}>Create 1k rows</button>
                <button onClick={create10k}>Create 10k rows</button>
                <button onClick={update}>Update every 10th row</button>
                <button onClick={select}>Select</button>
                <button onClick={swap}>Swap</button>
                <button onClick={remove}>Remove</button>
                <button onClick={clear}>Clear</button>
                <button onClick={runHeavy}>Run Heavy Calculation</button>
                <button onClick={runHeavyTask}>Run Heavy Calculation (Task Worker)</button>
                <button onClick={toggleFeed}>Start/Stop Real-time Feed</button>
            </div>
            <div className="right-pane">
                <div className="input-container">
                    <div className="spinner"></div>
                    <input type="text" placeholder="Typing test..." />
                </div>
                <div className="grid-container">
                    <Grid data={data} selected={selected} />
                </div>
            </div>
        </div>
    );
}

export default App;

// apps/interactive-benchmark-angular/src/app/app.component.ts
import { Component, ViewChild, ElementRef, AfterViewInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { DataService, RowData } from './data.service';
import { ColDef, GridApi, GridOptions, GridReadyEvent } from 'ag-grid-community';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  standalone: false
})
export class AppComponent implements AfterViewInit, OnDestroy {
  rowData: RowData[] = [];
  selectedRow: number | null = null;
  private gridApi!: GridApi;

  public gridOptions: GridOptions = {
    columnDefs: [
      { field: 'id', valueGetter: params => params.data.id, flex: 1 },
      { field: 'label', valueGetter: params => params.data.label, flex: 2 }
    ],
    rowSelection: 'single',
    getRowId: (params) => params.data.id,
    onGridReady: (params) => {
      this.gridApi = params.api;
    }
  };

  mainThreadCounter = 0;
  private counterInterval: any;
  private feedInterval: any;

  @ViewChild('heavyCalcOutput') heavyCalcOutput!: ElementRef;

  constructor(private dataService: DataService, private cdr: ChangeDetectorRef) {}

  ngAfterViewInit() {
    this.counterInterval = setInterval(() => {
      this.mainThreadCounter++;
      this.cdr.detectChanges(); // Manually trigger change detection
    }, 100);
  }

  ngOnDestroy() {
    clearInterval(this.counterInterval);
    if (this.feedInterval) {
      clearInterval(this.feedInterval);
    }
  }

  create10k() { this.rowData = this.dataService.buildData(10000); }
  create100k() { this.rowData = this.dataService.buildData(100000); }
  create1M() { this.rowData = this.dataService.buildData(1000000); }
  update() {
    const updatedData = this.dataService.updateData();
    this.gridApi.setGridOption('rowData', updatedData);
  }
  select() {
    if (this.gridApi && this.rowData.length > 0) {
      const visibleNodes = this.gridApi.getRenderedNodes();
      if (visibleNodes.length > 0) {
        const randomNode = visibleNodes[Math.floor(Math.random() * visibleNodes.length)];
        randomNode.setSelected(true);
        this.selectedRow = randomNode.data.id;
        this.gridApi.ensureNodeVisible(randomNode);
      }
    }
  }
  swap() {
    if (this.gridApi && this.rowData.length > 1) {
      const visibleNodes = this.gridApi.getRenderedNodes();
      if (visibleNodes.length > 1) {
        const node1 = visibleNodes[Math.floor(Math.random() * visibleNodes.length)];
        let node2 = visibleNodes[Math.floor(Math.random() * visibleNodes.length)];
        while (node1.id === node2.id) {
          node2 = visibleNodes[Math.floor(Math.random() * visibleNodes.length)];
        }

        const index1 = this.rowData.findIndex(d => d.id === node1.data.id);
        const index2 = this.rowData.findIndex(d => d.id === node2.data.id);

        const newData = [...this.rowData];
        [newData[index1], newData[index2]] = [newData[index2], newData[index1]];
        this.rowData = newData;
        this.gridApi.setGridOption('rowData', this.rowData);
      }
    }
  }
  remove() {
    if (this.rowData.length > 0) {
      const indexToRemove = Math.floor(Math.random() * this.rowData.length);
      const newData = [...this.rowData];
      newData.splice(indexToRemove, 1);
      this.rowData = newData;
      this.gridApi.setGridOption('rowData', this.rowData);
    }
  }
  clear() {
    this.rowData = this.dataService.clearData();
    this.selectedRow = null;
  }

  runHeavyCalculation() {
    // This will now be handled by the worker, but we can keep a main-thread version for comparison
    console.log('Heavy calculation started in Main Thread...');
    let result = 0;
    const iterations = 50000000;
    for (let i = 0; i < iterations; i++) {
        result += Math.sqrt(i) * Math.sin(i) / Math.cos(i) + Math.log(i + 1);
    }
    console.log('Heavy calculation finished in Main Thread. Result:', result);
    this.heavyCalcOutput.nativeElement.textContent = 'Finished!';
  }

  runHeavyTask() {
    console.log('Heavy calculation started in Task Worker...');
    const worker = new Worker(new URL('./heavy-computation.worker', import.meta.url), { type: 'module' });
    worker.onmessage = ({ data }) => {
      console.log('Heavy calculation finished in Task Worker. Result:', data);
      this.heavyCalcOutput.nativeElement.textContent = 'Finished!';
      worker.terminate();
    };
    worker.postMessage('start');
  }

  toggleFeed() {
    if (this.feedInterval) {
      clearInterval(this.feedInterval);
      this.feedInterval = null;
      console.log('Real-time feed stopped.');
    } else {
      console.log('Real-time feed started.');
      this.feedInterval = setInterval(() => {
        const updatedData = this.dataService.updateData();
        this.gridApi.setGridOption('rowData', updatedData);
      }, 5);
    }
  }
}
<div class="app-container">
  <div class="button-container">
    <button (click)="create10k()">Create 10k Rows</button>
    <button (click)="create100k()">Create 100k Rows</button>
    <button (click)="create1M()">Create 1M Rows</button>
    <button (click)="update()">Update Every 10th Row</button>
    <button (click)="select()">Select Row</button>
    <button (click)="swap()">Swap Rows</button>
    <button (click)="remove()">Remove Row</button>
    <button (click)="clear()">Clear Rows</button>
    <button (click)="runHeavyCalculation()">Run Heavy Calculation</button>
    <button (click)="runHeavyTask()">Run Heavy Calculation (Task Worker)</button>
    <button (click)="toggleFeed()">Start/Stop Real-time Feed</button>
  </div>
  <div class="right-pane">
    <div class="input-container">
      <div class="spinner"></div>
      <input type="text" placeholder="Type here to test UI responsiveness" />
      <div #heavyCalcOutput style="margin-left: 10px;"></div>
      <div style="margin-left: 10px; font-weight: bold; min-width: 8.2em;">Counter: {{ mainThreadCounter }}</div>
    </div>
    <div class="grid-container">
      <ag-grid-angular
        style="width: 100%; height: 100%;"
        class="ag-theme-quartz"
        [gridOptions]="gridOptions"
        [rowData]="rowData"
      >
      </ag-grid-angular>
    </div>
  </div>
</div>
